#set up properties
PROJECT_ID: qwiklabs-gcp-04-9265e3fc6464

server:
    port: ${DEFAULT_PORT:80}

spring:
    cloud:
        config:
            namespace: default
            enabled: true
            profile: dev, cloud, storage
            label: master
        gcp:
            credentials:
                location: classpath:key.json  
            storage:
                project-id: ${PROJECT_ID:qwiklabs-gcp-04-9265e3fc6464}
                enabled: true